name: drift_orm_codegen
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  # Drift
  drift:
  drift_orm:
    git:
      url: https://github.com/cdfq152313/drift_orm
      path: drift_orm
  drift_dev:

  # lib
  recase:

  # Build system, follow drift_dev's dependency constraints
  analyzer:
  build:
  build_config:
  dart_style:
  source_gen:

dev_dependencies:
  build_runner: ^2.4.0
  lints: ^6.0.0
  test: ^1.25.6

dependency_overrides:
  drift_orm:
    path: ../drift_orm
